  json.id deal.id
  json.product_id deal.product_id
  json.price deal.price
  json.url deal.url
  json.date deal.date
  json.comment deal.comment
  json.user_id deal.user_id
  json.created_at deal.created_at
  json.status deal.status