default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: broke_gamer_app_development

test:
  <<: *default
  database: broke_gamer_app_test

production:
  <<: *default
  database: broke_gamer_app_production
  username: broke_gamer_app
  password: <%= ENV['BROKE_GAMER_APP_DATABASE_PASSWORD'] %>
